# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: icyland/circleci-sonarscanner
      
    working_directory: /project

    steps:
      - checkout
      - run: run-sonar-scanner

      # run tests!
      #- run: phpunit
